In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Sztuczne dane do testów

In [2]:
X1 = np.random.default_rng(seed=42).integers(low=1, high=100, size=10000).tolist()
X2 = np.random.default_rng(seed=42).integers(low=1000, high=100000, size=10000).tolist()
X3 = np.random.default_rng(seed=42).integers(low=0, high=9, size=10000).tolist()
X = np.array(list(zip(X1, X2, X3)))

X_train = X[:8000, :]
X_test = X[8000:]

print('X_train:\n', X_train)
print('\nX_test:\n', X_test)

X_train:
 [[    9  9835     0]
 [   77 77621     6]
 [   65 65802     5]
 ...
 [   34 34626     3]
 [   14 14067     1]
 [   18 18855     1]]

X_test:
 [[   64 64941     5]
 [   71 71893     6]
 [   27 27485     2]
 ...
 [   35 35965     3]
 [   56 56985     5]
 [   61 61907     5]]


# StandardScaler

## Wbudowana funkcja

In [3]:
scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

print('X_train (StandardScaler):\n', X_train_sc)
print('\nX_test (StandardScaler):\n', X_test_sc)

X_train (StandardScaler):
 [[-1.42016928 -1.40846713 -1.53332949]
 [ 0.96283413  0.9672049   0.79467353]
 [ 0.54230412  0.55298857  0.40667303]
 ...
 [-0.54406509 -0.5396257  -0.36932798]
 [-1.24494844 -1.26014972 -1.14532899]
 [-1.10477177 -1.09234637 -1.14532899]]

X_test (StandardScaler):
 [[ 0.50725995  0.52281341  0.40667303]
 [ 0.75256912  0.7664577   0.79467353]
 [-0.78937426 -0.78989381 -0.75732848]
 ...
 [-0.50902092 -0.49269824 -0.36932798]
 [ 0.22690661  0.24398229  0.40667303]
 [ 0.40212744  0.41648188  0.40667303]]


## Własna funkcja

In [4]:
class standard_scaler:
    def __init__(self):
        self.X_train = None
        self.X_test = None
        self.mean = None
        self.std = None
        
    def FitTransform(self, X):
        self.X_train = X
        self.mean = [sum(self.X_train[:, idx]) / len(self.X_train[:, idx]) for idx in range(0, self.X_train.shape[1])]
        self.std = [np.sqrt(sum((self.X_train[:, idx] - self.mean[idx])**2) / self.X_train.shape[0]) for idx in range(0, self.X_train.shape[1])]

        return np.array(
            [
                [
                    (self.X_train[row, col] - self.mean[col]) / self.std[col]
                    for col in range(0, self.X_train.shape[1])
                ]
                for row in range(0, self.X_train.shape[0])
            ]
        )

    def Transform(self, X):
        self.X_test = X

        return np.array(
            [
                [
                    (self.X_test[row, col] - self.mean[col]) / self.std[col]
                    for col in range(0, self.X_test.shape[1])
                ]
                for row in range(0, self.X_test.shape[0])
            ]
        )

In [5]:
scaler2 = standard_scaler()

X_train_sc2 = scaler2.FitTransform(X_train)
X_test_sc2 = scaler2.Transform(X_test)

print('X_train (Class: standard_scaler):\n', X_train_sc2)
print('\nX_test (Class: standard_scaler):\n', X_test_sc2)

X_train (Class: standard_scaler):
 [[-1.42016928 -1.40846713 -1.53332949]
 [ 0.96283413  0.9672049   0.79467353]
 [ 0.54230412  0.55298857  0.40667303]
 ...
 [-0.54406509 -0.5396257  -0.36932798]
 [-1.24494844 -1.26014972 -1.14532899]
 [-1.10477177 -1.09234637 -1.14532899]]

X_test (Class: standard_scaler):
 [[ 0.50725995  0.52281341  0.40667303]
 [ 0.75256912  0.7664577   0.79467353]
 [-0.78937426 -0.78989381 -0.75732848]
 ...
 [-0.50902092 -0.49269824 -0.36932798]
 [ 0.22690661  0.24398229  0.40667303]
 [ 0.40212744  0.41648188  0.40667303]]


# MinMaxScaler

## Wbudowana funkcja

In [6]:
scaler3 = MinMaxScaler()

X_train_min_max_sc = scaler3.fit_transform(X_train)
X_test_min_max_sc = scaler3.transform(X_test)

print('X_train (MinMaxScaler):\n', X_train_min_max_sc)
print('\nX_test (MinMaxScaler):\n', X_test_min_max_sc)

X_train (MinMaxScaler):
 [[0.08163265 0.08926406 0.        ]
 [0.7755102  0.77413716 0.75      ]
 [0.65306122 0.65472438 0.625     ]
 ...
 [0.33673469 0.33973893 0.375     ]
 [0.13265306 0.1320219  0.125     ]
 [0.17346939 0.18039727 0.125     ]]

X_test (MinMaxScaler):
 [[0.64285714 0.6460253  0.625     ]
 [0.71428571 0.71626455 0.75      ]
 [0.26530612 0.26759012 0.25      ]
 ...
 [0.34693878 0.35326746 0.375     ]
 [0.56122449 0.56564218 0.625     ]
 [0.6122449  0.6153714  0.625     ]]


## Własna funkcja

In [7]:
class min_max_scaler:
    def __init__(self):
        self.X_train = None
        self.X_test = None
        self.max = None
        self.min = None

    def FitTransform(self, X):
        self.X_train = X
        self.max = [np.max(self.X_train[:, idx]) for idx in range(0, self.X_train.shape[1])]
        self.min = [np.min(self.X_train[:, idx]) for idx in range(0, self.X_train.shape[1])]

        return np.array(
            [
                [
                    (self.X_train[row, col] - self.min[col]) / (self.max[col] - self.min[col])
                    for col in range(0, self.X_train.shape[1])
                ]
                for row in range(0, self.X_train.shape[0])
            ]
        )

    def Transform(self, X):
        self.X_test = X

        return np.array(
            [
                [
                    (self.X_test[row, col] - self.min[col]) / (self.max[col] - self.min[col])
                    for col in range(0, self.X_test.shape[1])
                ]
                for row in range(0, self.X_test.shape[0])
            ]
        )

In [8]:
scaler4 = min_max_scaler()

X_train_min_max_sc2 = scaler4.FitTransform(X_train)
X_test_min_max_sc2 = scaler4.Transform(X_test)

print('X_train (Class: min_max_scaler):\n', X_train_min_max_sc2)
print('\nX_test (Class: min_max_scaler):\n', X_test_min_max_sc2)

X_train (Class: min_max_scaler):
 [[0.08163265 0.08926406 0.        ]
 [0.7755102  0.77413716 0.75      ]
 [0.65306122 0.65472438 0.625     ]
 ...
 [0.33673469 0.33973893 0.375     ]
 [0.13265306 0.1320219  0.125     ]
 [0.17346939 0.18039727 0.125     ]]

X_test (Class: min_max_scaler):
 [[0.64285714 0.6460253  0.625     ]
 [0.71428571 0.71626455 0.75      ]
 [0.26530612 0.26759012 0.25      ]
 ...
 [0.34693878 0.35326746 0.375     ]
 [0.56122449 0.56564218 0.625     ]
 [0.6122449  0.6153714  0.625     ]]
