In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, mean_absolute_error, mean_squared_error, r2_score

# Metryki klasyfikacji
# 1. y_test - rzeczywiste numery klas
# 2. y_pred - przewidziane przez model numery klas

In [2]:
y_test_k = np.random.default_rng(seed=42).integers(low=0, high=5, size=10000)
y_pred_k = [y_test_k[idx] if x == 'y_test' else np.random.choice(np.delete([0, 1, 2, 3, 4], np.where(np.array([0, 1, 2, 3, 4]) == y_test_k[idx])[0]))
          for idx, x in enumerate(np.random.default_rng(seed=42).choice(['y_test', 'other_class'], size=10000, p=[0.85, 0.15]))]

## Confusion Matrix (Macierz Pomyłek)

### Własna funkcja

In [3]:
def ConfusionMatrix(y_test, y_pred):
    return np.array(
        [
            [
                [
                    1 if pred == col and test == row else 0 for test, pred in zip(y_test, y_pred)
                ].count(1)
                for col in range(0, len(np.unique(y_test)))
            ]
            for row in range(0, len(np.unique(y_test)))
        ]
    )

In [4]:
print(ConfusionMatrix(y_test_k, y_pred_k))

[[1706   79   71   83   83]
 [  76 1727   58   63   69]
 [  65   81 1766   87   78]
 [  81   69   79 1670   68]
 [  61   84   63   77 1656]]


### Wbudowana funkcja

In [5]:
print(confusion_matrix(y_test_k, y_pred_k))

[[1706   79   71   83   83]
 [  76 1727   58   63   69]
 [  65   81 1766   87   78]
 [  81   69   79 1670   68]
 [  61   84   63   77 1656]]


### Accuracy (Dokładność)

### Własna funkcja

In [6]:
def Accuracy(y_test, y_pred):
    return [1 if y_test[idx] == y_pred[idx] else 0 for idx in range(0, len(y_test))].count(1) / len(y_test)

In [7]:
print(Accuracy(y_test_k, y_pred_k))
print(Accuracy(y_test_k, y_pred_k)*100)

0.8525
85.25


### Wbudowana funkcja

In [8]:
print(accuracy_score(y_test_k, y_pred_k))
print(accuracy_score(y_test_k, y_pred_k)*100)

0.8525
85.25


### Recall (Czułość)

### Własna funkcja

In [9]:
def Recall(y_test, y_pred):
    matrix = ConfusionMatrix(y_test, y_pred)
    
    return [
        round(float(matrix[idx][idx] / sum(matrix[idx])), 8)
        for idx in range(0, len(np.unique(y_test)))
    ]

In [10]:
print(Recall(y_test_k, y_pred_k))

[0.84371909, 0.86653287, 0.85026481, 0.84900864, 0.85316847]


### Wbudowana funkcja

In [11]:
print(recall_score(y_test_k, y_pred_k, average=None))

[0.84371909 0.86653287 0.85026481 0.84900864 0.85316847]


### Precision (Precyzja)

### Własna funkcja

In [12]:
def Precision(y_test, y_pred):
    matrix = ConfusionMatrix(y_test, y_pred)
    
    return [
        round(float(matrix[idx][idx] / sum([row[idx:idx+1][0] for row in matrix])), 8)
        for idx in range(0, len(np.unique(y_test)))
    ]

In [13]:
print(Precision(y_test_k, y_pred_k))

[0.85771745, 0.84656863, 0.86696122, 0.84343434, 0.84749232]


### Wbudowana funkcja

In [14]:
print(precision_score(y_test_k, y_pred_k, average=None))

[0.85771745 0.84656863 0.86696122 0.84343434 0.84749232]


### F1-score

### Własna funkcja

In [15]:
def F1(y_test, y_pred):
    return [
        round(2 * (precision * recall) / (precision + recall), 8)
        for precision, recall in zip(Precision(y_test, y_pred), Recall(y_test, y_pred))
    ]

In [16]:
print(F1(y_test_k, y_pred_k))

[0.85066069, 0.85643442, 0.85853185, 0.84621231, 0.85032092]


### Wbudowana funkcja

In [17]:
print(f1_score(y_test_k, y_pred_k, average=None))

[0.85066068 0.85643442 0.85853184 0.84621231 0.85032092]


# Metryki regresji

## 1. y_test - rzeczywiste wartości
## 2. y_pred - przewidziane wartości przez model

In [18]:
y_test_r = np.random.default_rng(seed=42).uniform(low=100, high=2000, size=10000)
y_pred_r = np.random.default_rng(seed=42).uniform(low=50, high=2500, size=10000)

### MAE (Mean Absolute Error)

### Własna funkcja

In [19]:
def MAE(y_test, y_pred):
    return sum([abs(test - pred) for test, pred in zip(y_test, y_pred)]) / len(y_test)

In [20]:
print(MAE(y_test_r, y_pred_r))

227.98104960587918


### Wbudowana funkcja

In [21]:
print(mean_absolute_error(y_test_r, y_pred_r))

227.9810496058788


### MSE (Mean Squared Error)

### Własna funkcja

In [22]:
def MSE(y_test, y_pred):
    return sum([(test - pred)**2 for test, pred in zip(y_test, y_pred)]) / len(y_test)

In [23]:
print(MSE(y_test_r, y_pred_r))

75041.65671063517


### Wbudowana funkcja

In [24]:
print(mean_squared_error(y_test_r, y_pred_r))

75041.65671063526


### RMSE (Root Mean Squared Error)

### Własna funkcja

In [25]:
def RMSE(y_test, y_pred):
    return np.sqrt(MSE(y_test, y_pred))

In [26]:
print(RMSE(y_test_r, y_pred_r))

273.9373225952155


### Wbudowana funkcja

In [27]:
print(np.sqrt(mean_squared_error(y_test_r, y_pred_r)))

273.9373225952157


### R^2 (Współczynnik determinacji)

### Własna funkcja

In [28]:
def R2(y_test, y_pred):
    y_test_mean = sum(y_test) / len(y_test)
    return 1 - sum([(test - pred)**2 for test, pred in zip(y_test, y_pred)]) / sum([(test - y_test_mean)**2 for test in y_test])

In [29]:
print(R2(y_test_r, y_pred_r))

0.7497421889450724


### Wbudowana funkcja

In [30]:
print(r2_score(y_test_r, y_pred_r))

0.7497421889450708
